name: animated_text
description: Animated_Text for Flutter provides animated translation between the words by reusing the similar alphabets between them.
version: 1.0.5-null-safety
homepage: https://github.com/kawal7415/animated_text.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  #flutter_test:
  #  sdk: flutter